"""
Django settings for MothersGarage project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rml#ys%e!4$xaxbj$+9u_qpg@rn1u^77f%=-&a=%k)2-1pdy+j"


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django.contrib.gis",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "onboarding",
    "authentication",
    "payments",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # You can also configure ALGORITHM, SIGNING_KEY, etc. if you want advanced settings
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "MothersGarage.security_middleware.SecurityHeadersMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MothersGarage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MothersGarage.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "mgd",
        "USER": "postgres",
        "PASSWORD": "Gotyouwillis@1998",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"


# Additional settings for security
# Hardening for production
# SECURE_SSL_REDIRECT = True  # Force HTTPS
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = "DENY"
ALLOWED_HOSTS = ["*"]  # Adjust accordingly
DEBUG = True

#CORS_ALLOW_ALL_ORIGINS = False  # safer for production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # your frontend dev URL
    "http://127.0.0.1:3000",
    "http://192.168.1.65:19000",  # If using Expo Go
    "exp://192.168.1.65:19000"    # Alternative Expo format
    # "https://your-frontend-domain.com",  # for production
]
CORS_ALLOW_ALL_ORIGINS = True


GDAL_LIBRARY_PATH = r"C:\Users\willi\GDAL\.pixi\envs\default\Library\bin\gdal.dll"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "jamesokadibong@gmail.com"
EMAIL_HOST_PASSWORD = "mylm arrq gvwt cfku"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Paypal settings
PAYPAL_CLIENT_ID = (
    "AZD1ErVVH6cM_hUg_1UyB13kPixd_kp_JFEa8Dk7Zpq_WkctUjHWDK9fTeKexqd2bpMz9AgUU061sQzD"
)
PAYPAL_SECRET = (
    "EHa7dhzro__2yu7cBvQDBm_LreledoWGectOhwTdoQWmK3Gkogo_DvQKkQXtYs6JMyzSeZOCmXNBSub4"
)
PAYPAL_API_BASE = "https://api-m.sandbox.paypal.com"  # switch to live when ready

# Optional: expected recipient email
PAYPAL_MERCHANT_EMAIL = "sb-1sglf38950789@business.example.com"
