# Generated by Django 5.1.3 on 2025-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproviderregistration',
            name='credentials',
        ),
        migrations.AddField(
            model_name='pendingproviderregistration',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
