# onboarding/urls.py
from django.urls import path
from .views import (
    MainLandingView,
    UserTypeSelectionView,
    # MotherSignUpView,
    ProviderSignUpView,
    RequestEmailOTPView,
    VerifyEmailOTPView,
    MotherConsentView,
    ProviderAdminVerificationView,
    ProviderSubscriptionView,
    MotherDashboardView,
    # ProviderDashboardView,
    MotherSettingsView,
    ProviderSettingsView,
    InterestListView,
    ServiceTypeListView,
    PendingMotherSignUpView,
    AdminDashboardView,
    SuperAdminDashboardView,
    SuperAdminCreateAdminView,
    PendingProviderSignUpView,
    AdminDashboardView,
    SuperAdminDashboardView,
    AdminApproveProviderView,
    SuperAdminCreateAdminView,
    CheckMotherFirstTimeView,
    CompleteMotherTutorialView,
    CheckMotherFirstTimeView,
    CompleteMotherTutorialView,
    SearchProvidersView,
    ProviderWorkspaceOverviewView,
    SpecialitiesByServiceView,
)

urlpatterns = [
    path("landing", MainLandingView.as_view(), name="main_landing"),
    path("select_user_type", UserTypeSelectionView.as_view(), name="select_user_type"),
    # path("mother_signup", MotherSignUpView.as_view(), name="mother_signup"),
    path("mother_signup", PendingMotherSignUpView.as_view(), name="mother_signup"),
    path("request_email_otp", RequestEmailOTPView.as_view(), name="request_email_otp"),
    path("provider_signup", ProviderSignUpView.as_view(), name="provider_signup"),
    # path("request_email_otp", RequestEmailOTPView.as_view(), name="request_email_otp"),
    path("verify_email_otp", VerifyEmailOTPView.as_view(), name="verify_email_otp"),
    path("mother_consent", MotherConsentView.as_view(), name="mother_consent"),
    path(
        "admin_verify_provider",
        ProviderAdminVerificationView.as_view(),
        name="admin_verify_provider",
    ),
    path(
        "provider_subscription",
        ProviderSubscriptionView.as_view(),
        name="provider_subscription",
    ),
    path("mother_dashboard", MotherDashboardView.as_view(), name="mother_dashboard"),
    # path(
    #     "provider_dashboard", ProviderDashboardView.as_view(), name="provider_dashboard"
    # ),
    path("mother_settings", MotherSettingsView.as_view(), name="mother_settings"),
    path("provider_settings", ProviderSettingsView.as_view(), name="provider_settings"),
    path("interests", InterestListView.as_view(), name="interest_list"),
    path("service_types", ServiceTypeListView.as_view(), name="service_type_list"),
    path("search_providers", SearchProvidersView.as_view(), name="search_providers"),
    path(
        "provider/workspace-select",
        ProviderWorkspaceOverviewView.as_view(),
        name="provider-workspace-dashboard",
    ),
    path("admin_dashboard", AdminDashboardView.as_view(), name="admin_dashboard"),
    path(
        "check_mother_first_time",
        CheckMotherFirstTimeView.as_view(),
        name="check_mother_first_time",
    ),
    path(
        "complete_mother_tutorial",
        CompleteMotherTutorialView.as_view(),
        name="complete_mother_tutorial",
    ),
    path(
        "super_admin_dashboard",
        SuperAdminDashboardView.as_view(),
        name="super_admin_dashboard",
    ),
    path(
        "create_admin_user",
        SuperAdminCreateAdminView.as_view(),
        name="create_admin_user",
    ),
    path(
        "provider_signup_pending",
        PendingProviderSignUpView.as_view(),
        name="provider_signup_pending",
    ),
    path(
        "admin_approve_provider",
        AdminApproveProviderView.as_view(),
        name="admin_approve_provider",
    ),
    path(
        "check_mother_first_time",
        CheckMotherFirstTimeView.as_view(),
        name="check_mother_first_time",
    ),
    path(
        "complete_mother_tutorial",
        CompleteMotherTutorialView.as_view(),
        name="complete_mother_tutorial",
    ),
    path(
        "service-specialities",
        SpecialitiesByServiceView.as_view(),
        name="service_specialities",
    ),
]
